# Generated by Django 6.0.2 on 2026-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("rose", "Rose"),
                    ("system", "System"),
                ],
                default="system",
                max_length=10,
            ),
        ),
    ]
