# Generated by Django 6.0.2 on 2026-05-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="theme",
        ),
    ]
