# Generated by Django 6.0.2 on 2026-05-27 08:36

import models_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sketchmodel",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=models_library.models.cover_upload_path
            ),
        ),
    ]
