from .writer import CodeWriter
from .flow import FlowAnalyzer
from .translators import get_translator


class CodeGenerator:

    def __init__(self, graph):
        self.graph = graph
        self.nodes = graph.get("nodes", [])
        self.links = graph.get("links", [])
        self.ports = graph.get("ports", [])
        self._node_map = {n["id"]: n for n in self.nodes}
        self._port_map = {p["id"]: p for p in self.ports}

    def generate(self):
        analyzer = FlowAnalyzer(self.graph)
        flow = analyzer.analyze()

        w = CodeWriter()
        self._generate_header(w)
        self._generate_imports(w, flow)
        self._generate_model(w, flow)
        self._generate_data(w, flow)
        self._generate_training(w, flow)
        self._generate_main(w, flow)
        return str(w)

    # ========== HEADER & IMPORTS ==========

    def _generate_header(self, w):
        w.line("# Generated by SketchNet")
        w.line("")

    def _generate_imports(self, w, flow):
        w.line("import torch")
        w.line("import torch.nn as nn")
        w.line("import torch.optim as optim")
        w.line("from torch.utils.data import DataLoader, TensorDataset")
        w.line("import numpy as np")
        if flow.get("visualization"):
            w.line("import matplotlib.pyplot as plt")
        if not flow.get("is_sequential", True):
            w.line("")
            w.line("try:")
            w.indent()
            w.line("from sketchnet_runtime import AddBlock, ConcatBlock")
            w.dedent()
            w.line("except ImportError:")
            w.indent()
            w.line("import sys")
            w.line('print("sketchnet_runtime not installed.")')
            w.line('print("Install: pip install sketchnet-runtime")')
            w.line("sys.exit(1)")
            w.dedent()
        w.line("")

    # ========== MODEL CLASS ==========

    def _generate_model(self, w, flow):
        model_nodes = flow.get("model_nodes", [])
        if not model_nodes:
            return

        is_seq = flow.get("is_sequential", True)

        first_node = model_nodes[0]
        first_t = get_translator(first_node, self)
        in_features = first_t.input_features()

        w.line("class SketchNetModel(nn.Module):")
        w.indent()
        w.line("def __init__(self):")
        w.indent()
        w.line("super().__init__()")

        if in_features is None:
            w.line("# TODO: Resolve input features from data shape")
            in_features = "in_features"

        if is_seq:
            w.line("self.model = nn.Sequential(")
            w.indent()
            current_features = in_features
            for node in model_nodes:
                t = get_translator(node, self)
                t.init_code(w, is_sequential=True, in_features=current_features)
                next_features = self._next_in_features(t, current_features)
                current_features = (
                    next_features if next_features is not None else "in_features"
                )
            w.dedent()
            w.line(")")
        else:
            current_features = in_features
            for node in model_nodes:
                t = get_translator(node, self)
                t.init_code(w, is_sequential=False, in_features=current_features)
                next_features = self._next_in_features(t, current_features)
                current_features = (
                    next_features if next_features is not None else "in_features"
                )

        w.dedent()
        w.line("")
        w.line("def forward(self, x, phase='every_batch'):")
        w.indent()

        if is_seq:
            w.line("return self.model(x)")
        else:
            input_vars = {0: "x"}
            skip_vars = {}
            for node in model_nodes:
                t = get_translator(node, self)
                output_vars = t.forward_code(w, input_vars, skip_vars)
                skip_vars[node["id"]] = output_vars
                if model_nodes.index(node) < len(model_nodes) - 1:
                    next_node = model_nodes[model_nodes.index(node) + 1]
                    input_vars = self._build_input_vars(next_node, skip_vars)

        w.dedent()
        w.dedent()
        w.line("")

    def _next_in_features(self, translator, current_in):
        node = translator.node
        t = node["type"]

        if t == "layer":
            return node.get("numNeurons", 64)
        elif t == "neuron":
            return 1
        elif t == "conv2d":
            return node.get("filters", 32)
        elif t == "flatten":
            out = translator.output_features()
            return out if out is not None else "flattened_features"
        elif t in ("dropout", "batchnorm"):
            return current_in
        elif t in ("add", "concat"):
            return current_in
        return current_in

    # ========== DATA LOADING ==========

    def _generate_data(self, w, flow):
        preprocessing = flow["preprocessing"]["nodes"]
        if not preprocessing:
            return

        w.line("def load_data():")
        w.indent()
        w.line('"""Load and preprocess data."""')
        w.line("")

        var_table = {}
        for node in preprocessing:
            t = get_translator(node, self)
            input_vars = self._build_input_vars(node, var_table)
            output_vars = t.data_code(w, input_vars)
            var_table[node["id"]] = output_vars

        # Find variable that feeds into the model
        model_nodes = flow.get("model_nodes", [])
        data_var = self._find_model_input_var(model_nodes, var_table)

        optimizers = flow.get("optimizers", [])
        batch_size = optimizers[0].get("batchSize", 32) if optimizers else 32
        shuffle = optimizers[0].get("shuffle", True) if optimizers else True

        w.line(f"dataset = TensorDataset({data_var}, {data_var})")
        w.line(
            f"loader = DataLoader(dataset, batch_size={batch_size}, shuffle={shuffle})"
        )
        w.line("return loader")
        w.dedent()
        w.line("")

    def _find_model_input_var(self, model_nodes, var_table):
        """Find the variable name that feeds into the first model node."""
        if not model_nodes:
            for vars_list in var_table.values():
                if vars_list:
                    return vars_list[0]
            return "data"

        first_model = model_nodes[0]
        for link in self.links:
            if self._port_node_id(link["to"]) == first_model["id"]:
                src_node = self._port_node_id(link["from"])
                if src_node in var_table:
                    vars_list = var_table[src_node]
                    src_port_id = link["from"]
                    src_node_obj = self._node_map.get(src_node, {})
                    for j, op in enumerate(src_node_obj.get("outputPorts", [])):
                        if op["id"] == src_port_id and j < len(vars_list):
                            return vars_list[j]
                    return vars_list[0]

        for vars_list in var_table.values():
            if vars_list:
                return vars_list[0]
        return "data"

    # ========== TRAINING ==========

    def _generate_training(self, w, flow):
        optimizers = flow.get("optimizers", [])
        if not optimizers:
            return

        opt = optimizers[0]
        phases = flow.get("phases", {})
        epochs = opt.get("epochs", 10)
        grad_clip = opt.get("gradientClip")
        early_stop = opt.get("earlyStopping", False)
        patience = opt.get("earlyStoppingPatience", 10)

        loop_phases = {m: p for m, p in phases.items() if p["is_loop"]}
        eval_phases = {m: p for m, p in phases.items() if not p["is_loop"]}

        w.line("def train_model(model, loader, optimizer, loss_fn):")
        w.indent()
        w.line("train_losses = []")
        if eval_phases:
            w.line("val_losses = []")
        else:
            w.line("val_losses = []  # No eval phases configured")

        if early_stop and eval_phases:
            w.line("best_val_loss = float('inf')")
            w.line("patience_counter = 0")
            w.line("best_model_state = None")

        w.line(f"for epoch in range({epochs}):")
        w.indent()

        for mode in loop_phases:
            w.line(f"# Phase: {mode}")
            w.line("model.train()")
            w.line("total_loss = 0")
            w.line("for batch_x, batch_y in loader:")
            w.indent()
            w.line("optimizer.zero_grad()")
            w.line(f"pred = model(batch_x, phase='{mode}')")
            w.line("loss = loss_fn(pred, batch_y)")
            w.line("loss.backward()")
            if grad_clip:
                w.line(
                    f"torch.nn.utils.clip_grad_norm_(model.parameters(), {grad_clip})"
                )
            w.line("optimizer.step()")
            w.line("total_loss += loss.item()")
            w.dedent()
            w.line("train_losses.append(total_loss / len(loader))")

        if eval_phases:
            w.line("")
            w.line("model.eval()")
            w.line("val_loss = 0")
            w.line("with torch.no_grad():")
            w.indent()
            for mode in eval_phases:
                w.line(f"# Phase: {mode}")
                w.line("for batch_x, batch_y in loader:")
                w.indent()
                w.line(f"pred = model(batch_x, phase='{mode}')")
                w.line("loss = loss_fn(pred, batch_y)")
                w.line("val_loss += loss.item()")
                w.dedent()
            w.dedent()
            w.line("val_losses.append(val_loss / len(loader))")

        w.line(f"print(f'Epoch {{epoch+1}}/{epochs}')")

        if early_stop and eval_phases:
            w.line("")
            w.line("if val_losses[-1] < best_val_loss:")
            w.indent()
            w.line("best_val_loss = val_losses[-1]")
            w.line("patience_counter = 0")
            w.line(
                "best_model_state = {k: v.clone() for k, v in model.state_dict().items()}"
            )
            w.dedent()
            w.line("else:")
            w.indent()
            w.line("patience_counter += 1")
            w.line(f"if patience_counter >= {patience}:")
            w.indent()
            w.line("print(f'Early stopping at epoch {epoch+1}')")
            w.line("model.load_state_dict(best_model_state)")
            w.line("break")
            w.dedent()
            w.dedent()

        w.dedent()
        w.line("return train_losses, val_losses")
        w.dedent()
        w.line("")

    # ========== MAIN BLOCK ==========

    def _generate_main(self, w, flow):
        w.line('if __name__ == "__main__":')
        w.indent()
        w.line("loader = load_data()")
        w.line("model = SketchNetModel()")
        w.line("")

        optimizers = flow.get("optimizers", [])
        if optimizers:
            opt = optimizers[0]
            t = get_translator(opt, self)
            t.optimizer_code(w)
            w.line("")
            w.line(
                "train_losses, val_losses = train_model(model, loader, optimizer, loss_fn)"
            )
            w.line("")
            w.line("# Final evaluation")
            w.line("model.eval()")
            w.line("correct = 0")
            w.line("total = 0")
            w.line("with torch.no_grad():")
            w.indent()
            w.line("for batch_x, batch_y in loader:")
            w.indent()
            w.line("pred = model(batch_x, phase='last_batch')")
            w.line("_, predicted = torch.max(pred, 1)")
            w.line("total += batch_y.size(0)")
            w.line("correct += (predicted == batch_y).sum().item()")
            w.dedent()
            w.dedent()
            w.line("print(f'Accuracy: {100 * correct / total:.2f}%')")

        viz = flow.get("visualization")
        if viz:
            w.line("")
            t = get_translator(viz, self)
            t.training_code(w)

        w.dedent()

    # ========== HELPERS ==========

    def _build_input_vars(self, node, var_table):
        """Build input_vars dict for a node from upstream connections."""
        input_vars = {}
        for port_data in node.get("inputPorts", []):
            port_id = port_data["id"]
            port_index = port_data["index"]
            for link in self.links:
                if link["to"] == port_id:
                    src_node_id = self._port_node_id(link["from"])
                    src_port_id = link["from"]
                    if src_node_id in var_table:
                        vars_list = var_table[src_node_id]
                        src_node_obj = self._node_map.get(src_node_id, {})
                        for j, op in enumerate(src_node_obj.get("outputPorts", [])):
                            if op["id"] == src_port_id and j < len(vars_list):
                                input_vars[port_index] = vars_list[j]
                                break
                        else:
                            if vars_list:
                                input_vars[port_index] = vars_list[0]
                    break
        return input_vars

    def _port_node_id(self, port_id):
        if not port_id:
            return None
        parts = port_id.rsplit("_", 2)
        return parts[0] if len(parts) >= 3 else None

    def _links_to(self, node_id):
        return [l for l in self.links if self._port_node_id(l["to"]) == node_id]

    def get_links_to(self, node_id):
        return self._links_to(node_id)
