from .writer import CodeWriter
from .flow import FlowAnalyzer
from .translators import get_translator


class CodeGenerator:
    """Main code generator — uses flow analysis + translators."""

    def __init__(self, graph):
        self.graph = graph
        self.nodes = graph.get("nodes", [])
        self.links = graph.get("links", [])
        self.ports = graph.get("ports", [])
        self._node_map = {n["id"]: n for n in self.nodes}
        self._port_map = {p["id"]: p for p in self.ports}

    def generate(self):
        """Generate complete Python code."""
        # Analyze the graph
        analyzer = FlowAnalyzer(self.graph)
        flow = analyzer.analyze()

        w = CodeWriter()

        # Header
        self._generate_header(w, flow)

        # Imports
        self._generate_imports(w, flow)

        # Model class
        self._generate_model(w, flow)

        # Data loading
        self._generate_data(w, flow)

        # Training
        self._generate_training(w, flow)

        # Main block
        self._generate_main(w, flow)

        return str(w)

    def _generate_header(self, w, flow):
        w.line("# Generated by SketchNet")
        w.line("")

    def _generate_imports(self, w, flow):
        w.line("import torch")
        w.line("import torch.nn as nn")
        w.line("import torch.optim as optim")
        w.line("from torch.utils.data import DataLoader, TensorDataset")
        w.line("import numpy as np")

        has_viz = flow.get("visualization") is not None
        if has_viz:
            w.line("import matplotlib.pyplot as plt")

        # Runtime library import
        if not flow.get("is_sequential", True):
            w.line("")
            w.line("try:")
            w.indent()
            w.line("from sketchnet_runtime import AddBlock, ConcatBlock")
            w.dedent()
            w.line("except ImportError:")
            w.indent()
            w.line("import sys")
            w.line('print("sketchnet_runtime is not installed.")')
            w.line('print("Install: pip install sketchnet-runtime")')
            w.line("sys.exit(1)")
            w.dedent()

        w.line("")

    def _generate_model(self, w, flow):
        """Generate the model class using translators."""
        model_nodes = flow.get("model_nodes", [])
        if not model_nodes:
            return

        is_seq = flow.get("is_sequential", True)
        w.line("class SketchNetModel(nn.Module):")
        w.indent()
        w.line("def __init__(self):")
        w.indent()
        w.line("super().__init__()")

        if is_seq:
            w.line("self.model = nn.Sequential(")
            w.indent()
            for node in model_nodes:
                t = get_translator(node, self)
                t.init_code(w, is_sequential=True)
            w.dedent()
            w.line(")")
        else:
            for node in model_nodes:
                t = get_translator(node, self)
                t.init_code(w, is_sequential=False)

        w.dedent()
        w.line("")
        w.line("def forward(self, x):")
        w.indent()

        if is_seq:
            w.line("return self.model(x)")
        else:
            input_var = "x"
            skip_vars = {}
            for node in model_nodes:
                t = get_translator(node, self)
                input_var = t.forward_code(w, input_var, skip_vars)
                if input_var:
                    skip_vars[node["id"]] = input_var
            w.line(f"return {input_var}")

        w.dedent()
        w.dedent()
        w.line("")

    def _generate_data(self, w, flow):
        """Generate data loading function."""
        w.line("def load_data():")
        w.indent()
        w.line('"""Load and preprocess data."""')

        # Preprocessing nodes
        for node in flow["preprocessing"]["nodes"]:
            t = get_translator(node, self)
            t.data_code(w, input_var="X")

        # Placeholder data
        w.line("# TODO: Replace with actual dataset loading")
        w.line("X = torch.randn(1000, 784)  # features")
        w.line("y = torch.randint(0, 10, (1000,))  # labels")
        w.line("")
        w.line("X_train, y_train = X, y")
        w.line("X_test, y_test = X[:100], y[:100]")
        w.line("")

        # Batch size from first optimizer
        optimizers = flow.get("optimizers", [])
        batch_size = 32
        shuffle = True
        if optimizers:
            opt = optimizers[0]
            batch_size = opt.get("batchSize", 32)
            shuffle = opt.get("shuffle", True)

        w.line(f"train_dataset = TensorDataset(X_train, y_train)")
        w.line(f"test_dataset = TensorDataset(X_test, y_test)")
        w.line(
            f"train_loader = DataLoader(train_dataset, batch_size={batch_size}, shuffle={shuffle})"
        )
        w.line(
            f"test_loader = DataLoader(test_dataset, batch_size={batch_size}, shuffle=False)"
        )
        w.line("return train_loader, test_loader")
        w.dedent()
        w.line("")

    def _generate_training(self, w, flow):
        """Generate training and evaluation code."""
        optimizers = flow.get("optimizers", [])
        if not optimizers:
            w.line("# No optimizer configured — inference only")
            return

        opt = optimizers[0]  # First optimizer for now
        t = get_translator(opt, self)

        # Optimizer + loss config
        t.optimizer_code(w)
        w.line("")

        # Training loop
        epochs = opt.get("epochs", 10)
        early_stop = opt.get("earlyStopping", False)
        patience = opt.get("earlyStoppingPatience", 10)
        grad_clip = opt.get("gradientClip")

        w.line("def train_model(model, train_loader, val_loader, optimizer, loss_fn):")
        w.indent()
        w.line("train_losses = []")
        w.line("val_losses = []")

        if early_stop:
            w.line("best_val_loss = float('inf')")
            w.line("patience_counter = 0")
            w.line("best_model_state = None")

        w.line(f"for epoch in range({epochs}):")
        w.indent()
        w.line("model.train()")
        w.line("total_loss = 0")
        w.line("for batch_x, batch_y in train_loader:")
        w.indent()
        w.line("optimizer.zero_grad()")
        w.line("pred = model(batch_x)")
        w.line("loss = loss_fn(pred, batch_y)")
        w.line("loss.backward()")

        if grad_clip:
            w.line(f"torch.nn.utils.clip_grad_norm_(model.parameters(), {grad_clip})")

        w.line("optimizer.step()")
        w.line("total_loss += loss.item()")
        w.dedent()
        w.line("avg_loss = total_loss / len(train_loader)")
        w.line("train_losses.append(avg_loss)")
        w.line("")

        # Validation
        w.line("model.eval()")
        w.line("val_loss = 0")
        w.line("with torch.no_grad():")
        w.indent()
        w.line("for batch_x, batch_y in val_loader:")
        w.indent()
        w.line("pred = model(batch_x)")
        w.line("loss = loss_fn(pred, batch_y)")
        w.line("val_loss += loss.item()")
        w.dedent()
        w.dedent()
        w.line("avg_val = val_loss / len(val_loader)")
        w.line("val_losses.append(avg_val)")
        w.line(
            f"print(f'Epoch {{epoch+1}}/{epochs} - Train: {{avg_loss:.4f}} - Val: {{avg_val:.4f}}')"
        )

        if early_stop:
            w.line("")
            w.line("if avg_val < best_val_loss:")
            w.indent()
            w.line("best_val_loss = avg_val")
            w.line("patience_counter = 0")
            w.line(
                "best_model_state = {k: v.clone() for k, v in model.state_dict().items()}"
            )
            w.dedent()
            w.line("else:")
            w.indent()
            w.line("patience_counter += 1")
            w.line(f"if patience_counter >= {patience}:")
            w.indent()
            w.line("print(f'Early stopping at epoch {epoch+1}')")
            w.line("model.load_state_dict(best_model_state)")
            w.line("break")
            w.dedent()
            w.dedent()

        w.dedent()
        w.line("return train_losses, val_losses")
        w.dedent()
        w.line("")

    def _generate_main(self, w, flow):
        """Generate the main block."""
        w.line('if __name__ == "__main__":')
        w.indent()
        w.line("train_loader, test_loader = load_data()")
        w.line("model = SketchNetModel()")

        optimizers = flow.get("optimizers", [])
        if optimizers:
            w.line("train_losses, val_losses = train_model(")
            w.line("    model, train_loader, test_loader, optimizer, loss_fn")
            w.line(")")
            w.line("")
            w.line("# Evaluation")
            w.line("model.eval()")
            w.line("correct = 0")
            w.line("total = 0")
            w.line("with torch.no_grad():")
            w.indent()
            w.line("for batch_x, batch_y in test_loader:")
            w.indent()
            w.line("pred = model(batch_x)")
            w.line("_, predicted = torch.max(pred, 1)")
            w.line("total += batch_y.size(0)")
            w.line("correct += (predicted == batch_y).sum().item()")
            w.dedent()
            w.dedent()
            w.line("print(f'Accuracy: {100 * correct / total:.2f}%')")

        # Visualization
        viz = flow.get("visualization")
        if viz:
            w.line("")
            t = get_translator(viz, self)
            t.training_code(w)

        w.dedent()

    # Port helpers (same as before)
    def _port_node_id(self, port_id):
        if not port_id:
            return None
        parts = port_id.rsplit("_", 2)
        if len(parts) >= 3:
            return parts[0]
        return None

    def get_links_to(self, node_id):
        return [l for l in self.links if self._port_node_id(l["to"]) == node_id]

    def get_links_from(self, node_id):
        return [l for l in self.links if self._port_node_id(l["from"]) == node_id]
