# Generated by Django 6.0.2 on 2026-05-22 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_id",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("xlsx", "Excel"),
                            ("parquet", "Parquet"),
                            ("rar", "Image Set (RAR)"),
                            ("zip", "Image Set (ZIP)"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="datasets/")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="datasets/covers/"
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
