# Generated by Django 6.0.2 on 2026-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("rose", "Rose"),
                    ("dark-rose", "Dark Rose"),
                    ("forest", "Forest"),
                    ("forest-dark", "Forest Dark"),
                    ("honey", "Honey"),
                    ("honey-dark", "Honey Dark"),
                ],
                default="system",
                help_text="Select your preferred color theme",
                max_length=11,
            ),
        ),
    ]
