# Generated by Django 6.0.2 on 2026-05-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0002_alter_usersettings_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="collapse_left_sidebar",
            field=models.BooleanField(
                default=False, help_text="Collapse the left toolbar by default"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="collapse_right_sidebar",
            field=models.BooleanField(
                default=False, help_text="Collapse the right sidebar by default"
            ),
        ),
    ]
