from .model import ModelGenerator
from .data import DataGenerator
from .training import TrainingGenerator
from .viz import VizGenerator


class CodeGenerator:
    """Main code generator — orchestrates all sub-generators."""

    def __init__(self, graph):
        self.graph = graph
        self.nodes = graph.get("nodes", [])
        self.links = graph.get("links", [])
        self.ports = graph.get("ports", [])
        self._node_map = {n["id"]: n for n in self.nodes}
        self._port_map = {p["id"]: p for p in self.ports}

    def generate(self):
        """Generate complete Python code."""
        lines = []

        # Imports
        lines.append("# Generated by SketchNet")
        lines.append("import torch")
        lines.append("import torch.nn as nn")
        lines.append("import torch.optim as optim")
        lines.append("from torch.utils.data import DataLoader, TensorDataset")
        lines.append("import numpy as np")

        has_viz = any(n["type"] == "visualization" for n in self.nodes)
        if has_viz:
            lines.append("import matplotlib.pyplot as plt")
        lines.append("")

        # Model class
        ordered = self.topological_order()
        model_gen = ModelGenerator(self)
        model_nodes = [
            n
            for n in ordered
            if n["type"]
            in {
                "layer",
                "neuron",
                "conv2d",
                "flatten",
                "dropout",
                "batchnorm",
                "add",
                "concat",
            }
        ]
        model_code = model_gen.generate(model_nodes)
        if model_code:
            lines.extend(model_code)
            lines.append("")

        # Data loading
        data_gen = DataGenerator(self)
        lines.extend(data_gen.generate())
        lines.append("")

        # Training + Main
        train_gen = TrainingGenerator(self)
        lines.extend(train_gen.generate())
        lines.append("")

        # Visualization
        if has_viz:
            viz_gen = VizGenerator(self)
            lines.extend(viz_gen.generate())

        return "\n".join(lines)

    def get_node(self, node_id):
        return self._node_map.get(node_id)

    def get_port(self, port_id):
        return self._port_map.get(port_id)

    def get_links_to(self, node_id):
        """Get all links where target is this node."""
        return [l for l in self.links if self._port_target_node(l["to"]) == node_id]

    def get_links_from(self, node_id):
        """Get all links where source is this node."""
        return [l for l in self.links if self._port_source_node(l["from"]) == node_id]

    def _port_source_node(self, port_id):
        """Extract node ID from a port ID like 'nodeId_output_0'."""
        if not port_id:
            return None
        # Split from right: 'n1_output_0' -> ['n1', 'output', '0']
        # For param ports: 'n1_input_0_param_0' -> more parts
        parts = port_id.rsplit("_", 2)
        if len(parts) >= 3:
            return parts[0]
        return None

    def _port_target_node(self, port_id):
        """Same logic for target ports."""
        return self._port_source_node(port_id)

    def find_nodes_by_type(self, node_type):
        return [n for n in self.nodes if n["type"] == node_type]

    def topological_order(self):
        input_nodes = self.find_nodes_by_type("input-data")
        if not input_nodes:
            return self.nodes

        visited = set()
        result = []

        def dfs(node_id):
            if node_id in visited:
                return
            visited.add(node_id)
            links = self.get_links_from(node_id)
            for link in links:
                target = self._port_target_node(link["to"])
                if target:
                    dfs(target)
            result.append(node_id)

        for n in input_nodes:
            dfs(n["id"])

        result.reverse()
        return [self._node_map[nid] for nid in result if nid in self._node_map]

    def _find_model_boundary(self, ordered_nodes):
        """Split ordered nodes into preprocessing and model subgraphs."""
        model_types = {
            "layer",
            "neuron",
            "conv2d",
            "flatten",
            "dropout",
            "batchnorm",
            "add",
            "concat",
        }

        first_model_idx = -1
        for i, node in enumerate(ordered_nodes):
            if node["type"] in model_types:
                first_model_idx = i
                break

        if first_model_idx == -1:
            return {"preprocessing": ordered_nodes, "model": []}

        return {
            "preprocessing": ordered_nodes[:first_model_idx],
            "model": ordered_nodes[first_model_idx:],
        }
